# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r: bioc-devel
warnings_are_errors: false
cache: packages

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"
env: _R_CHECK_FORCE_SUGGESTS_="false"

services:
  - xvfb

before_install:
  - export DISPLAY=:99.0

r_packages:
  - covr
  - BiocManager

after_success:
  - Rscript -e 'library(covr); codecov()'
